### ISSUE TITLE
vbz compression compatibility with guppy_basecaller

### ISSUE THREAD

**Issue by nick-youngblut** [nanoporetech/ont_fast5_api#64]
The README docs don't seem to state whether guppy_basecaller can read vbz-compressed files, and if yes, what the difference in file reading speed is versus uncompressed fast5 files.

**Comment by fbrennen** [comment]
Hi @nick-youngblut -- we haven't stated this because all vaguely-recent versions of guppy are capable of reading any fast5 file produced by `ont_fast5_api` (including vbz-compressed ones). 

Vbz benchmarks are generally found in the [vbz_compression project](https://github.com/nanoporetech/vbz_compression), though I do note there is not actually a speed comparison of reading uncompressed vs vbz there. In basic use the speed of fast5 file reading is insignificant compared to the time it takes to basecall those reads, which is why we haven't mentioned it. It can matter for more advanced users running `guppy_basecall_server`, and there are special tools to address that which are covered in the [guppy documentation](https://community.nanoporetech.com/protocols/Guppy-protocol/v/gpb_2003_v1_revaa_14dec2018/guppy-basecall-server).

Is there a specific issue you're having?

**Comment by nick-youngblut** [comment]
Thanks @fbrennen! I'm not running into a specific issue. I just am trying to evaluate options for storing and processing Nanopore data, and it wasn't fully clear what the good/bad aspects of vbz compression were.
